const {
  TOKEN_SERVICE_SSL_CERT,
  TOKEN_SERVICE_SSL_KEY,
  TOKEN_SERVICE_CLIENT_ID = "fishreg",
  DEBUG,
  LISTEN_PORT = 3000,
  TOKEN_EXPIRY = 900,
  REFRESHTOKEN_EXPIRY = 604800,
  CODE_TOKEN_EXPIRY = 900,
  CODE_REFRESHTOKEN_EXPIRY = 604800,
  JWT_ISSUER = "fishreg",
  JWT_ALOGORITHM = "RS256",
  JWT_AUDIENCE = "users",
  MONGODB_HOST,
  MONGODB_PORT,
  MONGODB_USER,
  MONGODB_PASSWORD,
  MONGODB_DATABASE,
  MONGODB_SCHEMA,
  MONGODB_TLS_KEY_FILE,
  MONGODB_TLS_CERT_FILE,
  MONGODB_TLS_CA_FILE,
} = process.env;

const JWTCONFIG = Object.freeze({
  algorithm: JWT_ALOGORITHM,
  audience: JWT_AUDIENCE,
  issuer: JWT_ISSUER,
  noTimestamp: false,
});

const config = {
  TOKEN_SERVICE_SSL_CERT,
  TOKEN_SERVICE_SSL_KEY,
  TOKEN_SERVICE_CLIENT_ID,
  DEBUG,
  LISTEN_PORT,
  TOKEN_EXPIRY,
  REFRESHTOKEN_EXPIRY,
  CODE_TOKEN_EXPIRY,
  CODE_REFRESHTOKEN_EXPIRY,
  JWTCONFIG,
  MONGODB_HOST,
  MONGODB_PORT,
  MONGODB_USER,
  MONGODB_PASSWORD,
  MONGODB_DATABASE,
  MONGODB_SCHEMA,
  MONGODB_TLS_KEY_FILE,
  MONGODB_TLS_CERT_FILE,
  MONGODB_TLS_CA_FILE,
};

export default config;
